services:
  postgres:
    container_name: pm-postgres
    image: postgres:latest
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - /data/postgres:/data/postgres
    networks:
      - pm-postgres-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always

#  db-test:
#    image: postgres:latest
#    ports:
#      - "${POSTGRES_TEST_PORT}:5432"
#    environment:
#      POSTGRES_USER: ${POSTGRES_TEST_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_TEST_DB}
#    restart: always

  pgadmin:
    container_name: pm-pgadmin
    links:
      - postgres:postgres
    image: dpage/pgadmin4
    ports:
      - "${PG_ADMIN_INTERNAL_PORT}:${PG_ADMIN_EXTERNAL_PORT}"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    networks:
      - pm-postgres-network
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    restart: always

  app:
    container_name: lock-box-backend
    build: .
    restart: always
    ports:
      - '${APP_DOCKER_HOST}:${APP_DOCKER_PORT}:${PORT}'
    networks:
      - pm-postgres-network
    env_file:
      - ./.env
    depends_on:
      - postgres
      - pgadmin

networks:
  pm-postgres-network:
    driver: bridge